# Generated by Django 4.1.7 on 2023-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientData',
            fields=[
                ('chatNo', models.AutoField(primary_key=True, serialize=False)),
                ('chatId', models.IntegerField(max_length=10)),
                ('patientId', models.IntegerField(max_length=20)),
                ('request', models.TextField(max_length=1000)),
                ('response', models.TextField(max_length=1000)),
            ],
        ),
    ]
