# Generated by Django 4.1.7 on 2023-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorAuth',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=1000)),
                ('password', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='patientAuth',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=1000)),
                ('password', models.TextField(max_length=1000)),
            ],
        ),
    ]
